eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-client

  activemq:
    broker-url: tcp://127.0.0.1:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 5
      idle-timeout: 30000
      expiry-timeout: 0