spring:
  application:
    name: service-turbine
server:
  port: 8769
security:
  basic:
    enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: service-client,service-lucy
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
